/*
 * STEPPER_program.c
 *
 *  Created on: Dec 19, 2023
 *      Author: Saker
 */

#include"STD_TYPES.h"
#include"BIT_MATH.h"


#include"DIO_interface.h"
#include"DIO_config.h"

#include <util/delay.h>
#include "STEPPER_config.h"
#include "STEPPER_interface.h"
#include "STEPPER_private.h"



void STEPPER_voidRotateCW(u16 Copy_u16Angle)
{
	u16 Local_u16Iterations = Copy_u16Angle / 0.7031;

	for(u16 i = 0; i<Local_u16Iterations; i++)
	{
		DIO_u8SetPinValue(STEPPER_PORT,STEPPER_BLUE_PIN ,DIO_u8HIGH);
		DIO_u8SetPinValue(STEPPER_PORT,STEPPER_PINK_PIN ,DIO_u8LOW);
		DIO_u8SetPinValue(STEPPER_PORT,STEPPER_YELLOW_PIN ,DIO_u8LOW);
		DIO_u8SetPinValue(STEPPER_PORT,STEPPER_ORANGE_PIN ,DIO_u8LOW);
		_delay_ms(2);
		DIO_u8SetPinValue(STEPPER_PORT,STEPPER_BLUE_PIN ,DIO_u8LOW);
		DIO_u8SetPinValue(STEPPER_PORT,STEPPER_PINK_PIN ,DIO_u8HIGH);
		DIO_u8SetPinValue(STEPPER_PORT,STEPPER_YELLOW_PIN ,DIO_u8LOW);
		DIO_u8SetPinValue(STEPPER_PORT,STEPPER_ORANGE_PIN ,DIO_u8LOW);
		_delay_ms(2);
		DIO_u8SetPinValue(STEPPER_PORT,STEPPER_BLUE_PIN ,DIO_u8LOW);
		DIO_u8SetPinValue(STEPPER_PORT,STEPPER_PINK_PIN ,DIO_u8LOW);
		DIO_u8SetPinValue(STEPPER_PORT,STEPPER_YELLOW_PIN ,DIO_u8HIGH);
		DIO_u8SetPinValue(STEPPER_PORT,STEPPER_ORANGE_PIN ,DIO_u8LOW);
		_delay_ms(2);
		DIO_u8SetPinValue(STEPPER_PORT,STEPPER_BLUE_PIN ,DIO_u8LOW);
		DIO_u8SetPinValue(STEPPER_PORT,STEPPER_PINK_PIN ,DIO_u8LOW);
		DIO_u8SetPinValue(STEPPER_PORT,STEPPER_YELLOW_PIN ,DIO_u8LOW);
		DIO_u8SetPinValue(STEPPER_PORT,STEPPER_ORANGE_PIN ,DIO_u8HIGH);
		_delay_ms(2);
	}
}
void STEPPER_voidRotateACW(u16 Copy_u16Angle)
{

	u16 Local_u16Iterations = Copy_u16Angle / 0.7031;

	for(u16 i = 0; i<Local_u16Iterations; i++)
	{
		DIO_u8SetPinValue(STEPPER_PORT,STEPPER_BLUE_PIN ,DIO_u8LOW);
		DIO_u8SetPinValue(STEPPER_PORT,STEPPER_PINK_PIN ,DIO_u8LOW);
		DIO_u8SetPinValue(STEPPER_PORT,STEPPER_YELLOW_PIN ,DIO_u8LOW);
		DIO_u8SetPinValue(STEPPER_PORT,STEPPER_ORANGE_PIN ,DIO_u8HIGH);
		_delay_ms(2);
		DIO_u8SetPinValue(STEPPER_PORT,STEPPER_BLUE_PIN ,DIO_u8LOW);
		DIO_u8SetPinValue(STEPPER_PORT,STEPPER_PINK_PIN ,DIO_u8LOW);
		DIO_u8SetPinValue(STEPPER_PORT,STEPPER_YELLOW_PIN ,DIO_u8HIGH);
		DIO_u8SetPinValue(STEPPER_PORT,STEPPER_ORANGE_PIN ,DIO_u8LOW);
		_delay_ms(2);
		DIO_u8SetPinValue(STEPPER_PORT,STEPPER_BLUE_PIN ,DIO_u8LOW);
		DIO_u8SetPinValue(STEPPER_PORT,STEPPER_PINK_PIN ,DIO_u8HIGH);
		DIO_u8SetPinValue(STEPPER_PORT,STEPPER_YELLOW_PIN ,DIO_u8LOW);
		DIO_u8SetPinValue(STEPPER_PORT,STEPPER_ORANGE_PIN ,DIO_u8LOW);
		_delay_ms(2);
		DIO_u8SetPinValue(STEPPER_PORT,STEPPER_BLUE_PIN ,DIO_u8HIGH);
		DIO_u8SetPinValue(STEPPER_PORT,STEPPER_PINK_PIN ,DIO_u8LOW);
		DIO_u8SetPinValue(STEPPER_PORT,STEPPER_YELLOW_PIN ,DIO_u8LOW);
		DIO_u8SetPinValue(STEPPER_PORT,STEPPER_ORANGE_PIN ,DIO_u8LOW);
		_delay_us(2);
	}
}
void STEPPER_voidStop()
{
	DIO_u8SetPinValue(STEPPER_PORT,STEPPER_BLUE_PIN ,DIO_u8LOW);
	DIO_u8SetPinValue(STEPPER_PORT,STEPPER_PINK_PIN ,DIO_u8LOW);
	DIO_u8SetPinValue(STEPPER_PORT,STEPPER_YELLOW_PIN ,DIO_u8LOW);
	DIO_u8SetPinValue(STEPPER_PORT,STEPPER_ORANGE_PIN ,DIO_u8LOW);
}


